# The revised simplex algorithm

In [67]:
import numpy as np

In [68]:
A = np.array(
    [[3, 2, 1, 2, 1, 0, 0], [1, 1, 1, 1, 0, 1, 0], [4, 3, 3, 4, 0, 0, 1]], dtype=int
)
A

array([[3, 2, 1, 2, 1, 0, 0],
       [1, 1, 1, 1, 0, 1, 0],
       [4, 3, 3, 4, 0, 0, 1]])

In [69]:
b = np.array([225, 117, 420], dtype=int)
b

array([225, 117, 420])

In [70]:
c = np.array([19, 13, 12, 17, 0, 0, 0], dtype=int)
c

array([19, 13, 12, 17,  0,  0,  0])

In [71]:
base = np.zeros(A.shape[1], dtype=bool)
base[[0, 2, 6]] = True
base

array([ True, False,  True, False, False, False,  True])

In [72]:
A[..., base]

array([[3, 1, 0],
       [1, 1, 0],
       [4, 3, 1]])

In [73]:
A[..., ~base]

array([[2, 2, 1, 0],
       [1, 1, 0, 1],
       [3, 4, 0, 0]])

In [74]:
A_B_inv = np.linalg.inv(A[..., base])
A_B_inv

array([[ 0.5, -0.5,  0. ],
       [-0.5,  1.5, -0. ],
       [-0.5, -2.5,  1. ]])

In [75]:
c[base] @ A_B_inv @ b

1782.0

In [76]:
p = A_B_inv @ b
p

array([54., 63., 15.])

In [77]:
B = A[..., base]
B

array([[3, 1, 0],
       [1, 1, 0],
       [4, 3, 1]])

In [78]:
# c_N - c_B B^-1 A_N

# Find:
#     y = c_B @ B^-1
# by solving
#     yB = c_B

y = c[base] @ A_B_inv
y

array([3.5, 8.5, 0. ])

In [79]:
z = c[~base] - y @ A[..., ~base]
z

array([-2.5,  1.5, -3.5, -8.5])

In [80]:
# Example calculating only one element
index = 0
c[~base][index] -  y @ A[..., ~base][..., index]

-2.5

In [81]:
entering = np.where(~base)[0][z.argmax()]
entering

3

In [82]:
# Find d = B^-1 a
# where
#     a - is the entering column (A_N[..., entering])

In [83]:
a = A[..., entering]
a

array([2, 1, 4])

In [84]:
d = A_B_inv @ a
d

array([0.5, 0.5, 0.5])

In [91]:
valid = np.where(d > 0)[0]

bounds = p[valid] / d[valid]
arg_min_bound = bounds.argmin()

min_bound = bounds[arg_min_bound]
leaving_rel = valid[arg_min_bound]
leaving = np.where(base)[0][leaving_rel]

leaving, leaving_rel, min_bound

(6, 2, 30.0)

In [88]:
p_new = p - min_bound * d 
p_new[leaving_rel] = min_bound
p_new

array([39., 48., 30.])

In [93]:
base[entering] = True
base[leaving] = False
base

array([ True, False,  True,  True, False, False, False])